METHOD CHAINING

In [1]:
import pandas as pd

In [2]:
path_1 = "data/mexico-real-estate-1.csv"

In [3]:
df = pd.read_csv(path_1)
df.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

In [4]:
df.shape

(700, 6)

In [5]:
df.dropna()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
5,house,Yucatán,21.052583,-89.538639,205.0,"$105,191.37"
...,...,...,...,...,...,...
693,house,Puebla,19.051815,-98.277669,198.0,"$115,910.26"
694,apartment,Distrito Federal,19.309208,-99.171906,70.0,"$77,572.89"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

In [6]:
df = pd.read_csv(path_1)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 52.7 KB

In [7]:
df = pd.read_csv(path_1)
df.dtypes

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object

In [8]:
(
    pd.read_csv(path_1)
    .isnull()
        .sum()
)

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64

In [9]:
### dropping missing values
(pd.read_csv(path_1)
 .dropna()
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
5,house,Yucatán,21.052583,-89.538639,205.0,"$105,191.37"
...,...,...,...,...,...,...
693,house,Puebla,19.051815,-98.277669,198.0,"$115,910.26"
694,apartment,Distrito Federal,19.309208,-99.171906,70.0,"$77,572.89"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

In [10]:
df.assign(
    price_usd = lambda x:
    x["price_usd"]
    .str.replace("$","", regex=False)
    .str.replace(",","",regex=False)
    .astype(float)
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,67965.56
1,house,Nuevo León,25.688436,-100.198807,186.0,63223.78
2,apartment,Guerrero,16.767704,-99.764383,82.0,84298.37
3,apartment,Guerrero,16.829782,-99.911012,150.0,94308.80
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,94835.67
...,...,...,...,...,...,...
695,house,Morelos,NaN,NaN,310.0,237089.17
696,house,Yucatán,21.050653,-89.558841,334.0,137017.34
697,house,Yucatán,21.343796,-89.262060,130.0,110404.35
698,apartment,Nuevo León,NaN,NaN,155.0,184446.42
699,house,Querétaro,20.587378,-100.418361,106.0,56637.97

In [11]:
df1 = pd.read_csv(path_1).dropna()
df1['price_usd']= pd.to_numeric(df1['price_usd'].str.replace("$","").str.replace(",",""))

In [12]:
path_2 = "data/mexico-real-estate-2.csv"

In [13]:
path_3 = "data/mexico-real-estate-3.csv"

In [14]:
df2 =( 
    pd.read_csv(path_2)
    .assign(price_usd = lambda x: x["price_mxn"].div(19))
    .drop(columns=["price_mxn"])
    .dropna()
)

print(f"df2 type: {type(df2)}")
print(f"df2 shape: {df2.shape}")
df2.head()

df2 type: <class 'pandas.DataFrame'>
df2 shape: (571, 6)

,property_type,state,lat,lon,area_m2,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,39904.736842

In [15]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",",expand=True)
    .dropna()
    .head()
)

            0            1
0    19.52589   -99.151703
1  19.2640539  -99.5727534
2   19.268629   -99.671722
4   19.511938   -96.871956
5   20.689157  -103.366728

In [16]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",",expand=True)[0]
    .dropna()
    .astype(float)
    .head()
)

0    19.525890
1    19.264054
2    19.268629
4    19.511938
5    20.689157
Name: 0, dtype: float64

In [17]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",",expand=True)[1]
    .dropna()
    .astype(float)
    .head()
)

0    -99.151703
1    -99.572753
2    -99.671722
4    -96.871956
5   -103.366728
Name: 1, dtype: float64

In [18]:
(
    pd.read_csv(path_3)
    ["place_with_parent_names"]
    .head()
)

0    |México|Distrito Federal|Gustavo A. Madero|Acu...
1             |México|Estado de México|Toluca|Metepec|
2    |México|Estado de México|Toluca|Toluca de Lerd...
3          |México|Morelos|Temixco|Burgos Bugambilias|
4    |México|Veracruz de Ignacio de la Llave|Veracruz|
Name: place_with_parent_names, dtype: str

In [19]:
(
    pd.read_csv(path_3)
    ["place_with_parent_names"]
    .str.split("|", expand=True)
    .head()
)

,0,1,2,3,4,5,6
0,,México,Distrito Federal,Gustavo A. Madero,Acueducto de Guadalupe,,NaN
1,,México,Estado de México,Toluca,Metepec,,NaN
2,,México,Estado de México,Toluca,Toluca de Lerdo,Ocho Cedros,
3,,México,Morelos,Temixco,Burgos Bugambilias,,NaN
4,,México,Veracruz de Ignacio de la Llave,Veracruz,,NaN,NaN

In [31]:
# cleaning process using method chaining
df3 = (
    pd.read_csv(path_3)
    # Drop null values from df3
    .dropna()
    # Create "lat" and "lon" columns for df3
    .assign(lat=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[0]           
                .astype(float),
            lon=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[1]           
                .astype(float),
            # Create "state" column for df3
            state=lambda x: x["place_with_parent_names"]
            .str.split("|", expand=True)[2]
           )
    
    # Drop "place_with_parent_names" and "lat-lon" from df3
    .drop(columns=["place_with_parent_names", "lat-lon"])
            
    
)

# Print object type, shape, and head
print("df3 type:", type(df3))
print("df3 shape:", df3.shape)
df3.head()

df3 type: <class 'pandas.DataFrame'>
df3 shape: (582, 6)

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.00,"48,550.59",19.53,-99.15,Distrito Federal
1,house,233.00,"168,636.73",19.26,-99.57,Estado de México
2,house,300.00,"86,932.69",19.27,-99.67,Estado de México
4,apartment,84.00,"68,508.67",19.51,-96.87,Veracruz de Ignacio de la Llave
5,house,175.00,"102,763.00",20.69,-103.37,Jalisco

In [21]:
# Check if all column sets are identical
columns_match = set(df1) == set(df2) == set(df3)

if columns_match:
    print("✅ All DataFrames have the same columns.")
else:
    print("❌ Column mismatch detected!")
    # Optional: See the difference
    print("df1 vs df2 diff:", set(df1.columns) ^ set(df2.columns))
    print("df2 vs df3 diff:", set(df2.columns) ^ set(df3.columns))

✅ All DataFrames have the same columns.

In [25]:
# Stack df1, df2, and df3 vertically
df = pd.concat([df1,df2,df3], ignore_index=True)

# Verify the result
print(f"Combined Shape: {df.shape}")
print(f"row count: {df.shape[0]}")
df.index
df.head()

Combined Shape: (1736, 6)
row count: 1736

  property_type             state        lat         lon  area_m2  price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   67965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   63223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   84298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   94308.80
4         house           Yucatán  21.052583  -89.538639    205.0  105191.37

In [27]:
# Save your cleaned combined dataset
df.to_csv("./data/mexico-real-estate-combined-clean.csv", index=False)

In [30]:
# Summarize the numeric columns
summary = df[["price_usd", "area_m2"]].describe()

# # Format for readability
pd.options.display.float_format = '{:,.2f}'.format

summary

       price_usd  area_m2
count   1,736.00 1,736.00
mean  115,331.98   170.26
std    65,426.17    80.59
min    33,157.89    60.00
25%    65,789.47   101.75
50%    99,262.13   156.00
75%   150,846.66   220.00
max   326,733.66   385.00